name: code-fair-AMD-OCT-paper
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.11.4
  - ipykernel = 6.19.2
  - openpyxl = 3.0.10
  - ipywidgets
  - pip
  - pip:
      - pandas == 1.5.3
      - matplotlib == 3.7.1
      - seaborn == 0.12.2